version: "3.7"

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - ws1
      - ws2
      - ws3
      - ws4
  rds:
    image: redis
  ws1:
    image: wsapp
    environment:
      - APPID=1111
    depends_on:
      - rds
  ws2:
    image: wsapp
    environment:
      - APPID=2222
    depends_on:
      - rds
  ws3:
    image: wsapp
    environment:
      - APPID=3333
    depends_on:
      - rds
  ws4:
    image: wsapp
    environment:
      - APPID=4444
    depends_on:
      - rds
